import { useEffect, useState } from "react";

type Report={id:number;bank_name:string;country_name:string;report_title:string;report_url:string;reporting_period_end?:string;period_label?:string;processed_at?:string;status:string};
type Metric={bank_name:string;country_name:string;metric_label:string;value:number;unit:string;period_label?:string;reporting_period_end?:string;source_url:string;source_title?:string};
type Props={token:string;onBack:()=>void};
async function api(path:string,token:string){const r=await fetch(path,{headers:{Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||r.statusText);return b}
export default function Review({token,onBack}:Props){const [reports,setReports]=useState<Report[]>([]),[metrics,setMetrics]=useState<Metric[]>([]),[error,setError]=useState(""),[tab,setTab]=useState<"reports"|"metrics">("reports");
 async function load(){try{const x=await api("/api/admin/audit?limit=500",token);setReports(x.reports||[]);setMetrics(x.metrics||[])}catch(e){setError(String(e))}}
 useEffect(()=>{load()},[]);
 return <section className="shell page"><div className="section-head"><div><span className="kicker">Audit trail</span><h1>Published financial data</h1><p className="lead">BankLens now publishes automatically from configured official reporting portals. This screen lets you audit what was downloaded, what was extracted, and the exact source behind each public number.</p></div><div style={{display:"flex",gap:8}}><button className="text-button" onClick={onBack}>← Admin</button><button className="button small" onClick={load}>Refresh</button></div></div><div className="admin-stats"><div><b>{reports.length}</b><span>Reports processed</span></div><div><b>{metrics.length}</b><span>Published values</span></div><div><b>{new Set(metrics.map(x=>x.bank_name)).size}</b><span>Banks covered</span></div></div>{error&&<aside className="notice"><b>Audit error</b><p>{error}</p></aside>}<div style={{display:"flex",gap:8,marginBottom:16}}><button className={tab==="reports"?"button small":"text-button"} onClick={()=>setTab("reports")}>Reports ({reports.length})</button><button className={tab==="metrics"?"button small":"text-button"} onClick={()=>setTab("metrics")}>Extracted values ({metrics.length})</button></div>{tab==="reports"?<div className="panel"><div className="table-wrap"><table><thead><tr><th>Bank</th><th>Country</th><th>Report</th><th>Period</th><th>Processed</th><th/></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td><b>{r.bank_name}</b></td><td>{r.country_name}</td><td>{r.report_title}</td><td>{r.period_label||r.reporting_period_end||"—"}</td><td>{r.processed_at?new Date(r.processed_at).toLocaleString():"—"}</td><td><a href={r.report_url} target="_blank" rel="noreferrer">Download report ↗</a></td></tr>)}</tbody></table></div></div>:<div className="panel"><div className="table-wrap"><table><thead><tr><th>Bank</th><th>Metric</th><th>Value</th><th>Period</th><th>Reference</th></tr></thead><tbody>{metrics.map((m,i)=><tr key={`${m.bank_name}-${m.metric_label}-${m.reporting_period_end}-${i}`}><td><b>{m.bank_name}</b><small>{m.country_name}</small></td><td>{m.metric_label}</td><td><b>{m.value}</b> {m.unit}</td><td>{m.period_label||m.reporting_period_end||"—"}</td><td><a href={m.source_url} target="_blank" rel="noreferrer">{m.source_title||"Financial report"} ↗</a></td></tr>)}</tbody></table></div></div>}</section>
}
